### ISSUE TITLE
Give examples of how to use iron-media-query with e.g. layout

### ISSUE THREAD

**Issue by grokys** [PolymerElements/iron-media-query#12]
For example in 0.5 you could do something like:

    <iron-media-query query="max-width: 640px" querymatches="{{smallScreen}}"></iron-media-query>
    <div layout vertical?="{{smallScreen}}">

How would you do this in polymer 1.0?

**Comment by blasten** [comment]
You could take a look at the demo: https://github.com/PolymerElements/iron-media-query/blob/master/demo/index.html#L32

In the case of `<div layout vertical?="{{smallScreen}}">`, these are now named **layout classes**.

e.g: `<div class="layout vertical">` 

That means that you need to compute the classes you want to apply.

eg: `<div class$="[[_computeClasses(smallScreen)]]">` and define a JS function inside your `Polymer({..})`

```javascript
_computeClasses: function(smallScreen) {
   return (smallScreen) ? 'layout vertical': 'layout';
}
```
For more details, check out the docs: https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#annotated-computed
