### ISSUE TITLE
https://elements.polymer-project.org/elements/iron-media-query

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/iron-media-query#13]
_From @samuelcardillo on June 21, 2015 15:57_

The documentation is giving the attribute "queryMatches" 
```html 
<iron-media-query query="(min-width: 600px)" queryMatches="{{queryMatches}}"></iron-media-query>
```

which is not working as the good attribute is "query-matches" 
```html 
<iron-media-query query="(min-width: 600px)" query-matches="{{queryMatches}}"></iron-media-query>
```

_Copied from original issue: Polymer/polymer-element-catalog#139_

**Comment by notwaldorf** [comment]
The documentation was already fixed in the last release, but I think the catalog hasn't been updated yet to pick it up.
