### ISSUE TITLE
<div hidden$="">

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/iron-media-query#16]
view-source:https://elements.polymer-project.org/bower_components/iron-media-query/demo/index.html

Isn't it recommended to use `<div hidden$="">` 

https://www.polymer-project.org/1.0/docs/devguide/templates.html#dom-if

```text
...will be slower as it must create the second screen from scratch rather than simply showing that screen. Hiding/showing elements is as simple as attribute-binding to the hidden attribute (e.g. <div hidden$="">), and does not require conditional templating at all...
```

People like me blindly copy the demo code so I would make sure to do it the recommended way even if it looks ugly.

**Comment by notwaldorf** [comment]
If you think of this demo as representing a mobile-or-desktop layout, then most of the time you probably only need to stamp one of the layouts, but not both (unless you're playing with the webinspector, on a desktop you should get the desktop layout, and on mobile, always the smaller layout). If you would have used `hidden` in the demo, then both layouts would get created, but only one ever shown, which is much slower.

I think the paragraph you linked to says that if you're going to show most of the divs, creating them once, at load time, and then toggling their visibility is better. However, that's not the intention of this demo.

/cc @blasten who worked on the demo recently
