### ISSUE TITLE
Demo should show responsive layout based on the media query

### ISSUE THREAD

**Issue by arthurevans** [PolymerElements/iron-media-query#20]
The current demo shows a pretty atypical use case -- swapping content using `dom-if` -- rather than changing layouts based on media queries, for example. See this email thread:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/polymer-dev/mhP92As7pr8/hwRzAMsgCwAJ

**Comment by notwaldorf** [comment]
Here's the JSBin referenced in the email thread that could be added to the demo (or something similar, maybe prettier): http://jsbin.com/yekiqa/2/edit?html,output

**Comment by arthurevans** [comment]
Definitely something prettier :D Pretty demos are not my strong suit.
