### ISSUE TITLE
Print of the demo fails in Chrome

### ISSUE THREAD

**Issue by zoechi** [PolymerElements/iron-media-query#28]
![image](https://cloud.githubusercontent.com/assets/405837/11088130/2849a42e-8860-11e5-8cf4-913e683b461e.png)
In firefox print preview and print works, but `(http://polymer-project.org)` isn't shown.

- Chrome: 46.0.2490.80  
- Firefox: 42.0
On Debian Linux

**Comment by bicknellr** [comment]
Yeah, reproable:
![screen shot 2015-11-17 at 12 04 42](https://cloud.githubusercontent.com/assets/406614/11223249/d765caba-8d23-11e5-8124-aa79b0d7c517.png)
The print preview works if you go directly to the demo page though:
![screen shot 2015-11-17 at 12 03 54](https://cloud.githubusercontent.com/assets/406614/11223237/ca6dfdfa-8d23-11e5-9645-554eeb5ad3f8.png)
This is a Chrome bug - the page should never be able to cause previews / printing to fail. This might be tricky to reduce though.

Firefox successfully previews but the demo doesn't work as intended:
![screen shot 2015-11-17 at 12 11 34](https://cloud.githubusercontent.com/assets/406614/11223778/83135f74-8d26-11e5-8c40-c84ec8ac1949.png)
[This bug](https://bugzilla.mozilla.org/show_bug.cgi?id=774398) looks like the source of the problem.

**Comment by bicknellr** [comment]
This seems to be a more general issue: Polymer/polymer#2518.

**Comment by ebidel** [comment]
Let's use that one to track.
