### ISSUE TITLE
There is an error with the queryMatches

### ISSUE THREAD

**Issue by harrinsonmb** [PolymerElements/iron-media-query#6]
There is an error in the documentation, because if we use:

    <iron-media-query query="(min-width: 600px)" queryMatches="{{queryMatches}}"></iron-media-query>    

the variable queryMatches appears to be undefined, but if we use:

    <iron-media-query query="(min-width: 600px)" query-matches="{{queryMatches}}"></iron-media-query>    

the feature works fine.

Detected from: http://stackoverflow.com/questions/30533573/polymer-iron-media-query-not-working-as-previous-versions/30535299#30535299

**Comment by notwaldorf** [comment]
That makes sense (attributes should be dash-cased). Thanks for finding it!

**Comment by harrinsonmb** [comment]
Thanks to @travellhyne :D
